from distutils.core import setup
import py2exe
import os
import sys

# Define the entry point script (your main script)
main_script = 'your_script.py'

# List of additional modules or packages that your script depends on
additional_modules = [
    'module1',
    'module2',
    'package.submodule',
    # Add more modules or packages as needed
]

# Create a list of data files (e.g., non-Python files your script depends on)
data_files = []

# Include data files (e.g., configuration files) by specifying their paths
data_files.append(('config', ['config.ini']))
data_files.append(('data', ['data_file.txt']))
# Add more data files as needed

# Create a dictionary of options for py2exe
options = {
    'py2exe': {
        'compressed': 1,      # Create a compressed executable
        'optimize': 2,        # Optimize the generated bytecode
        'bundle_files': 3,    # Create a single executable with all libraries
        'dist_dir': 'dist'    # Output directory for the generated executable
    }
}

# Use the setup function to create the executable
setup(
    console=[main_script],  # List of entry point scripts
    zipfile=None,           # Do not create a separate zip file
    options=options,        # py2exe options
    data_files=data_files,  # List of data files
    windows=[{              # Optional: Create a Windows application instead of a console application
        'script': main_script,
        'icon_resources': [(0, 'app_icon.ico')],
    }],
)

# Clean up temporary py2exe files
if os.path.exists('build'):
    import shutil
    shutil.rmtree('build')

# Optionally, display a message to indicate successful completion
print("Executable built successfully. Find it in the 'dist' directory.")
input("Press Enter to exit.")
